version: '2'
services:
  elastic:
    image: elasticsearch:7.14.2
    container_name: elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - client.transport.sniff=true

  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql1/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
volumes:
  db_data: